### ISSUE TITLE
NoMethodError: undefined method `[]' for nil:NilClass error when trying to use custom platforms

### ISSUE THREAD

**Issue by midasgossye** [Arduino-CI/action#21]
Hi,

I tried to define an additional platform (the Arduino nano every) by putting the following configs in a ```.arduino-ci.yml``` file in the root directory of a library I want to test with CI. I used the description in [this issue ](https://github.com/Arduino-CI/arduino_ci/issues/138) as a basis. You can find the github repo with all of the files I used here: [github.com/Whaddadraft/VMA430_GPS_Module](https://github.com/Whaddadraft/VMA430_GPS_Module)

```yaml
packages:
  arduino:megaavr:
    url: https://downloads.arduino.cc/packages/package_index.json

platfoms:

  nano_every:
        board: arduino:megaavr:nona4809
        package: arduino:megaavr
        gcc:
          features:
          defines:
            - MILLIS_USE_TIMERB3
            - NO_EXTERNAL_I2C_PULLUP
            - AVR_NANO_4809_328MODE
          warnings:
          flags:

compile:
  # Choosing to run compilation tests on 2 different Arduino platforms
  platforms:
    - uno
    - leonardo
    - mega2560
    - cplayClassic
    - nano_every

```

Unfortunately, this resuls in the following errors being thrown, and I don't know how to procede now to try to fix the issue...

```
Beginning the next phase of testing...           Compilation of example sketches

Discovered example sketch...                              Show_time_location.ino
Wildcard architecture in library.properties, using configured platforms... 
    uno
    leonardo
    mega2560
    cplayClassic
    nano_every
...Wildcard architecture in library.properties, using configured platforms      
Board package arduino:avr has a defined URL...                                 ✓
Installing board package arduino:avr...                                        ✓
Compiling Show_time_location.ino for arduino:avr:uno...                        ✓
Compiling Show_time_location.ino for arduino:avr:leonardo...                   ✓
Compiling Show_time_location.ino for arduino:avr:mega:cpu=atmega2560...        ✓
Compiling Show_time_location.ino for arduino:avr:circuitplay32u4cat...         ✓
bundler: failed to load command: /action/bundle/ruby/2.6.0/bin/arduino_ci.rb (/action/bundle/ruby/2.6.0/bin/arduino_ci.rb)
NoMethodError: undefined method `[]' for nil:NilClass
  /action/bundle/ruby/2.6.0/gems/arduino_ci-1.3.0/exe/arduino_ci.rb:478:in `block (2 levels) in perform_example_compilation_tests'
  /action/bundle/ruby/2.6.0/gems/arduino_ci-1.3.0/exe/arduino_ci.rb:477:in `each'
  /action/bundle/ruby/2.6.0/gems/arduino_ci-1.3.0/exe/arduino_ci.rb:477:in `block in perform_example_compilation_tests'
  /action/bundle/ruby/2.6.0/gems/arduino_ci-1.3.0/exe/arduino_ci.rb:457:in `each'
  /action/bundle/ruby/2.6.0/gems/arduino_ci-1.3.0/exe/arduino_ci.rb:457:in `perform_example_compilation_tests'
  /action/bundle/ruby/2.6.0/gems/arduino_ci-1.3.0/exe/arduino_ci.rb:536:in `<top (required)>'
  /action/bundle/ruby/2.6.0/bin/arduino_ci.rb:23:in `load'
  /action/bundle/ruby/2.6.0/bin/arduino_ci.rb:23:in `<top (required)>'
```

Any clues would be greatly appreciated :)
