### ISSUE TITLE
action failing because of missing python-pip

### ISSUE THREAD

**Issue by feilipu** [Arduino-CI/action#22]
I've looked at the Issues log and there's a few resolved issues (eg #20) around the python-pip module being missing.

`E: Package 'python-pip' has no installation candidate`

I've tried to change the action to v0.1.2 from stable, and this doesn't resolve the problem.
Could you please point to the current correct resolution for this issue?
TIA.

Current `arduino_ci.yml`.

```yaml
---
name: Arduino_CI

on: [push, pull_request]

jobs:
  arduino_ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: Arduino-CI/action@v0.1.2  # or latest, or a pinned version
```

[Arduino_FreeRTOS_Library](https://github.com/feilipu/Arduino_FreeRTOS_Library)
